import { Button } from "../../../shared/components/ui/button";
import type { ProjectDockerStatus } from "../types/project.types";

interface ProjectDockerPanelProps {
  isBusy: boolean;
  status?: ProjectDockerStatus;
  onGenerate: () => void;
  onRefresh: () => void;
  onRestart: () => void;
  onStart: () => void;
  onStop: () => void;
}

const STATE_LABELS: Record<ProjectDockerStatus["state"], string> = {
  failed: "Failed",
  notGenerated: "Not generated",
  running: "Running",
  stopped: "Stopped",
  unavailable: "Unavailable",
};

export function ProjectDockerPanel({
  isBusy,
  onGenerate,
  onRefresh,
  onRestart,
  onStart,
  onStop,
  status,
}: ProjectDockerPanelProps) {
  return (
    <section className="grid gap-4 border-2 border-voicebox-black bg-white p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="font-mono text-xs uppercase text-voicebox-secondary">Project Docker</p>
          <h2 className="mt-1 font-display text-2xl uppercase leading-none text-voicebox-black">
            Compose Runtime
          </h2>
        </div>
        <Button disabled={isBusy} onClick={onRefresh} variant="secondary">
          Refresh
        </Button>
      </div>

      {status ? (
        <div className="grid gap-2 border border-voicebox-border bg-voicebox-surface p-3">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <p className="font-mono text-xs uppercase text-voicebox-secondary">
              {status.composeProjectName}
            </p>
            <span className="border-2 border-voicebox-black bg-white px-2 py-1 font-mono text-xs uppercase text-voicebox-black">
              {STATE_LABELS[status.state]}
            </span>
          </div>
          <p className="text-sm font-semibold text-voicebox-black">{status.statusMessage}</p>
          {status.url ? (
            <a
              className="break-all font-mono text-xs text-voicebox-black underline decoration-2 underline-offset-4"
              href={status.url}
              rel="noreferrer"
              target="_blank"
            >
              {status.url}
            </a>
          ) : null}
          {status.composeFilePath ? (
            <p className="break-all font-mono text-xs text-voicebox-secondary">
              {status.composeFilePath}
            </p>
          ) : null}
          {status.containerId ? (
            <p className="break-all font-mono text-xs text-voicebox-secondary">
              Container: {status.containerId}
            </p>
          ) : null}
        </div>
      ) : (
        <p className="text-sm text-voicebox-secondary">
          Docker status is loaded per project. Compose files are generated by the Rust backend in an
          app-owned runtime directory.
        </p>
      )}

      <div className="flex flex-wrap gap-2">
        <Button disabled={isBusy} onClick={onGenerate} variant="secondary">
          Generate Compose
        </Button>
        <Button disabled={isBusy} onClick={onStart}>
          Start Docker
        </Button>
        <Button disabled={isBusy} onClick={onStop} variant="secondary">
          Stop Docker
        </Button>
        <Button disabled={isBusy} onClick={onRestart} variant="secondary">
          Restart Docker
        </Button>
      </div>
    </section>
  );
}
